"""Canonical wire values from docs/LoopGraph_03_Data_Models_API_Contracts.md."""

from enum import StrEnum


class LoopStatus(StrEnum):
    ACTIVE = "ACTIVE"
    WAITING = "WAITING"
    BLOCKED = "BLOCKED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class NodeStatus(StrEnum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    WAITING = "WAITING"
    BLOCKED = "BLOCKED"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    SUPERSEDED = "SUPERSEDED"


class EdgeType(StrEnum):
    DEPENDS_ON = "DEPENDS_ON"
    PROVES = "PROVES"
    BLOCKS = "BLOCKS"
    TRIGGERS = "TRIGGERS"
    SUPERSEDES = "SUPERSEDES"
    CONTRADICTS = "CONTRADICTS"


class EventType(StrEnum):
    MESSAGE_RECEIVED = "MESSAGE_RECEIVED"
    MESSAGE_SENT = "MESSAGE_SENT"
    DOCUMENT_CREATED = "DOCUMENT_CREATED"
    DOCUMENT_UPDATED = "DOCUMENT_UPDATED"
    DOCUMENT_FOUND = "DOCUMENT_FOUND"
    CALENDAR_EVENT_CREATED = "CALENDAR_EVENT_CREATED"
    CALENDAR_EVENT_UPDATED = "CALENDAR_EVENT_UPDATED"
    CALENDAR_EVENT_DELETED = "CALENDAR_EVENT_DELETED"
    DEADLINE_REACHED = "DEADLINE_REACHED"
    ACTION_COMPLETED = "ACTION_COMPLETED"
    ACTION_FAILED = "ACTION_FAILED"
    USER_APPROVED = "USER_APPROVED"
    USER_REJECTED = "USER_REJECTED"
    USER_INPUT = "USER_INPUT"
    SYSTEM_EVENT = "SYSTEM_EVENT"


class EvidenceRelationship(StrEnum):
    PROVES = "PROVES"
    CONTRADICTS = "CONTRADICTS"
    SUPERSEDES = "SUPERSEDES"
    PARTIALLY_SUPPORTS = "PARTIALLY_SUPPORTS"
    INSUFFICIENT = "INSUFFICIENT"
    UNRELATED = "UNRELATED"


class ActionStatus(StrEnum):
    PROPOSED = "PROPOSED"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    APPROVED = "APPROVED"
    EXECUTING = "EXECUTING"
    EXECUTED = "EXECUTED"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ApprovalStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class GraphOperationType(StrEnum):
    ADD_NODE = "ADD_NODE"
    UPDATE_NODE = "UPDATE_NODE"
    SUPERSEDE_NODE = "SUPERSEDE_NODE"
    CANCEL_NODE = "CANCEL_NODE"
    VERIFY_NODE = "VERIFY_NODE"
    ADD_EDGE = "ADD_EDGE"
    REMOVE_EDGE = "REMOVE_EDGE"
    UPDATE_DEADLINE = "UPDATE_DEADLINE"
    ADD_EVIDENCE_REQUIREMENT = "ADD_EVIDENCE_REQUIREMENT"
    UPDATE_EVIDENCE_REQUIREMENT = "UPDATE_EVIDENCE_REQUIREMENT"
    ADD_ACTION = "ADD_ACTION"
    CANCEL_ACTION = "CANCEL_ACTION"
